let library = [{
    title: 'Dark Angels of Darkness',
    artist: 'Al Gofa',
    about: 'A group of elite soldiers plot to overthrow a god, by perfecting the illegal act of FUSION. But if you plan to kill a god, you gotta be ready for divine punishment too. A book filled to the edges with raw muscle and A+ level action. We hope you have fun.',
    year: '2017',
    pages: 170,
    measurements: '15 x 19,5',
    printInfo: '3 color offset',
    coverWeb: '../public/img/daod_cover@500x645.jpg',
    coverMobile: '../public/img/daod_cover@300x387.jpg',
    galleryWeb: ['../public/img/daod_cover@500x645.jpg', '../public/img/daod_page01@500x650.jpg', '../public/img/daod_page02@500x650.jpg', '../public/img/daod_page03@500x650.jpg', '../public/img/daod_page04@500x650.jpg', '../public/img/daod_page05@500x650.jpg'],
    galleryMobile: [],
    priceUSD: 25,
    priceDigital: 18,
    digital: true, 
    button: 'BUY',
},
{
    title: 'Heat',
    artist: 'Jean Wei',
    about: 'Beatuiful slice-of-life centered on a naked 8-foot fire demon demon and farm life with an old Aunt and grand-niece. Sounds pretty spicy if you ask me. And you know what they say about spicy. Spicy is HEAT.',
    year: '2018',
    pages: 121,
    measurements: '16 x 23',
    printInfo: '3 color offset',
    coverWeb: '../public/img/heat_cover@500x706.jpg',
    coverMobile: '../public/img/heat@300x424.jpg',
    galleryWeb: ['../public/img/heat_cover@500x706.jpg', '../public/img/heat_p01@1000x703.jpg', '../public/img/heat_p02@1000x703.jpg', '../public/img/heat_p03@1000x703.jpg'],
    galleryMobile: [],
    priceUSD: 18,
    priceDigital: 15,
    digital: true,
    button: 'BUY',
},
{
    title: 'Junky',
    artist: 'Guillaume Singelin',
    about: 'Treasure of art and behind the scenes look in the sketchbook and drawing worlds of Guillaume Singelin, master king French comic artist. The majority of the book is printed in 2 layers of ink to preserve the original red pencil linework and a separate black ink layer. The book also includes 4 color sections.',
    year: '2017',
    pages: 220,
    measurements: '18 x 23.5',
    printInfo: '2 & 4 color offset',
    coverWeb: '../public/img/junky_cover@500x649.jpg',
    coverMobile: '../public/img/junky_cover@300x389.jpg',
    galleryWeb: ['../public/img/junky_cover@500x649.jpg', '../public/img/junky_p01@500x653.jpg', '../public/img/junky_p02@500x653.jpg', '../public/img/junky_p03@500x653.jpg','../public/img/junky_p04@500x653.jpg'],
    galleryMobile: [],
    priceUSD: 25,
    priceDigital: 18,
    digital: true,
    button: 'BUY',
}];

export default library;